openapi: 3.0.2
info:
  title: Links and Institutions
  version: 1.20.1
  description:
    $ref: ./markdown/BelvoApiIntroduction.md
  contact:
    name: Need help?
    url: 'https://developers.belvo.com'
    email: support@belvo.com
  x-logo:
    url: 'https://files.readme.io/5111448-belvo-for-developers.svg'
    altText: Belvo logo
servers:
  - url: 'https://sandbox.belvo.com'
    description: Sandbox
  - url: 'https://development.belvo.com'
    description: Development
security:
  - basicAuth: []
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description:
        $ref: ./markdown/BelvoBasicAuthentication.md
tags:
  - name: Institutions
    description:
      $ref: ./markdown/Institutions.md
  - name: Links
    description:
      $ref: ./markdown/Links.md
paths:
  /api/institutions/:
    $ref: paths/api@institutions@.yaml
  '/api/institutions/{id}/':
    $ref: 'paths/api@institutions@{id}@.yaml'
  /api/links/:
    $ref: paths/api@links@.yaml
  '/api/links/{id}/':
    $ref: 'paths/api@links@{id}@.yaml'
x-readme:
  explorer-enabled: true
  proxy-enabled: true
  samples-enabled: true
  samples-languages: ['curl', 'node', 'ruby', 'python']
